function [vector, cls] = trainOnSet(set)
%Give this a set generated by generateDataset and it will return a training
%vector and a class vector in form [vector, class]


vector = [];
cls = [];


h = waitbar(0,'0%','Name','Generating Training Vectors...',...
            'CreateCancelBtn',...
            'setappdata(gcbf,''canceling'',1)');
setappdata(h,'canceling',0)

for k = 1:length(set)
    if getappdata(h,'canceling')
        break
    end
    G = set{1,k};
    
    exclude = bwmorph(G < 10, 'dilate', 10);
    valids = ~exclude(:);
    useResponse = response(valids,:);
    
    
    
    vector = [vector; useResponse];
    
    binary = set{2,k};
    useBinary = binary(valids);
    cls = [cls; useBinary(:)];
    
    
    if(0 == 0)
        waitbar(k/length(set),h,sprintf('%d%% complete', round(100*(k/length(set))) ) );
    end
end
delete(h)